services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: msclientes
      POSTGRES_USER: Isaias
      POSTGRES_PASSWORD: 1234
      TZ: America/Guayaquil
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - red-ms
    restart: always

  ms-clientes:
    image: isaiasurb/ms-clientes:latest
    container_name: ms-clientes
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/msclientes
      SPRING_DATASOURCE_USERNAME: Isaias
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_PORT: 8081
    depends_on:
      - postgres
    networks:
      - red-ms
    restart: always

volumes:
  db_data:
    name: isaias_ms_clientes_pgdata

networks:
  red-ms:
    driver: bridge